remote: false

experienceLevel:
  internship: false
  entry: false
  associate: true
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - Software developer
  - Python developer
  - Backend engineer
  - Software engineer

locations:
  - Fountain Valley
  - Irvine
  - Los Angeles

distance: 50

companyBlacklist:
  - CyberCoders

titleBlacklist:
